import Footer from './components/Footer';
import Header from './components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh',
            width: '100vw',
            padding: '20px',
            boxSizing: 'border-box',
            backgroundColor: '#f0f0f0',
            border: '1px solid #ccc',
          }}
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
